version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      REDIS_URL: rediss://default:AYjlAAIncDE4Yjg4NGE2ZWExY2I0NTNmYWIyOWM2YzMyNTUyOGE2N3AxMzUwNDU@proven-gazelle-35045.upstash.io:6379
      RABBITMQ_URL: amqps://trufeodz:X9OLf7Uawv0ibqpdKxRn1ePGwFBFOZxG@puffin.rmq2.cloudamqp.com/trufeodz
      MONGODB_URI: mongodb+srv://harshsharmahs081:WSAZJ6pK9SZvDp6k@cluster0.e7634ss.mongodb.net/
      IDENTITY_SERVICE_URL: http://identity-service:3001
      POST_SERVICE_URL: http://post-service:3002
      MEDIA_SERVICE_URL: http://media-service:3003
      SEARCH_SERVICE_URL: http://search-service:3004
    depends_on:
      - identity-service
      - post-service
      - media-service
      - search-service

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REDIS_URL: rediss://default:AYjlAAIncDE4Yjg4NGE2ZWExY2I0NTNmYWIyOWM2YzMyNTUyOGE2N3AxMzUwNDU@proven-gazelle-35045.upstash.io:6379
      RABBITMQ_URL: amqps://trufeodz:X9OLf7Uawv0ibqpdKxRn1ePGwFBFOZxG@puffin.rmq2.cloudamqp.com/trufeodz
      MONGODB_URI: mongodb+srv://harshsharmahs081:WSAZJ6pK9SZvDp6k@cluster0.e7634ss.mongodb.net/

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      REDIS_URL: rediss://default:AYjlAAIncDE4Yjg4NGE2ZWExY2I0NTNmYWIyOWM2YzMyNTUyOGE2N3AxMzUwNDU@proven-gazelle-35045.upstash.io:6379
      RABBITMQ_URL: amqps://trufeodz:X9OLf7Uawv0ibqpdKxRn1ePGwFBFOZxG@puffin.rmq2.cloudamqp.com/trufeodz
      MONGODB_URI: mongodb+srv://harshsharmahs081:WSAZJ6pK9SZvDp6k@cluster0.e7634ss.mongodb.net/

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      REDIS_URL: rediss://default:AYjlAAIncDE4Yjg4NGE2ZWExY2I0NTNmYWIyOWM2YzMyNTUyOGE2N3AxMzUwNDU@proven-gazelle-35045.upstash.io:6379
      RABBITMQ_URL: amqps://trufeodz:X9OLf7Uawv0ibqpdKxRn1ePGwFBFOZxG@puffin.rmq2.cloudamqp.com/trufeodz
      MONGODB_URI: mongodb+srv://harshsharmahs081:WSAZJ6pK9SZvDp6k@cluster0.e7634ss.mongodb.net/

  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      REDIS_URL: rediss://default:AYjlAAIncDE4Yjg4NGE2ZWExY2I0NTNmYWIyOWM2YzMyNTUyOGE2N3AxMzUwNDU@proven-gazelle-35045.upstash.io:6379
      RABBITMQ_URL: amqps://trufeodz:X9OLf7Uawv0ibqpdKxRn1ePGwFBFOZxG@puffin.rmq2.cloudamqp.com/trufeodz
      MONGODB_URI: mongodb+srv://harshsharmahs081:WSAZJ6pK9SZvDp6k@cluster0.e7634ss.mongodb.net/
