services:
  - name: redis
    type: redis
    plan: free
    ipAllowList:
      - group: all

  - name: api-gateway
    type: web
    plan: free
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: MESSAGE_BROKER_URL
        sync: false
      - key: IDENTITY_SERVICE_URL
        fromService:
          type: web
          name: identity-service
          property: url
      - key: POST_SERVICE_URL
        fromService:
          type: web
          name: post-service
          property: url
      - key: MEDIA_SERVICE_URL
        fromService:
          type: web
          name: media-service
          property: url
      - key: SEARCH_SERVICE_URL
        fromService:
          type: web
          name: search-service
          property: url
      - key: MONGO_URI
        sync: false

  - name: identity-service
    type: web
    plan: free
    env: docker
    dockerfilePath: ./identity-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: MESSAGE_BROKER_URL
        sync: false
      - key: MONGO_URI
        sync: false

  - name: post-service
    type: web
    plan: free
    env: docker
    dockerfilePath: ./post-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: MESSAGE_BROKER_URL
        sync: false
      - key: MONGO_URI
        sync: false

  - name: media-service
    type: web
    plan: free
    env: docker
    dockerfilePath: ./media-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: MESSAGE_BROKER_URL
        sync: false
      - key: MONGO_URI
        sync: false

  - name: search-service
    type: web
    plan: free
    env: docker
    dockerfilePath: ./search-service/Dockerfile
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: MESSAGE_BROKER_URL
        sync: false
      - key: MONGO_URI
        sync: false
